version: '2'
services:
  db:
    image: jmarmuszewski/pg-training:tmp_sessions
    ports:
      - "5432:5432"
  web:
    build: the_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./the_app:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
